name: Build with MSBuild

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v2

            - name: Build project
              run: cd ComPortProxy; msbuild /p:Configuration=Release

            - name: Publish UI artifacts
              uses: actions/upload-artifact@v4
              with:
                    name: built-artifacts
                    path: ./ComPortProxy/ComPortProxy.Ui/bin/Release

            - name: Publish artifacts
              uses: actions/upload-artifact@v4
              with:
                    name: built-artifacts
                    path: ./ComPortProxy/ComPortProxy/bin/Release